set(headers
	BSModelDB.h
	Colors.h
	CustomMenu.h
	GameAPI.h
	GameBSExtraData.h
	GameCamera.h
	GameData.h
	GameEvents.h
	GameExtraData.h
	GameFormComponents.h
	GameForms.h
	GameHandlers.h
	GameInput.h
	GameMenus.h
	GameObjects.h
	GamePathing.h
	GameRTTI.h
	GameRTTI.inl
	GameReferences.h
	GameResources.h
	GameSettings.h
	GameStreams.h
	GameTypes.h
	GameUtilities.h
	GlobalLocks.h
	HashUtil.h
	Hooks_Camera.h
	Hooks_Data.h
	Hooks_Debug.h
	Hooks_Diagnostics.h
	Hooks_DirectInput8Create.h
	Hooks_Event.h
	Hooks_Gameplay.h
	Hooks_Handlers.h
	Hooks_Memory.h
	Hooks_NetImmerse.h
	Hooks_ObScript.h
	Hooks_Papyrus.h
	Hooks_SaveLoad.h
	Hooks_Scaleform.h
	Hooks_Threads.h
	Hooks_UI.h
	InputMap.h
	InternalSerialization.h
	InternalTasks.h
	NiAdditionalGeometryData.h
	NiControllers.h
	NiExtraData.h
	NiGeometry.h
	NiInterpolators.h
	NiLight.h
	NiMaterial.h
	NiNodes.h
	NiObjects.h
	NiProperties.h
	NiRTTI.h
	NiRenderer.h
	NiSerialization.h
	NiTextures.h
	NiTypes.h
	ObScript.h
	PapyrusActiveMagicEffect.h
	PapyrusActor.h
	PapyrusActorBase.h
	PapyrusActorValueInfo.h
	PapyrusAlias.h
	PapyrusAmmo.h
	PapyrusArgs.h
	PapyrusArmor.h
	PapyrusArmorAddon.h
	PapyrusArt.h
	PapyrusBook.h
	PapyrusCamera.h
	PapyrusCell.h
	PapyrusClass.h
	PapyrusColorForm.h
	PapyrusCombatStyle.h
	PapyrusConstructibleObject.h
	PapyrusDefaultObjectManager.h
	PapyrusDelayFunctors.h
	PapyrusEnchantment.h
	PapyrusEquipSlot.h
	PapyrusEventFunctor.h
	PapyrusEvents.h
	PapyrusFaction.h
	PapyrusFlora.h
	PapyrusForm.h
	PapyrusFormList.h
	PapyrusGame.h
	PapyrusGameData.h
	PapyrusHeadPart.h
	PapyrusIngredient.h
	PapyrusInput.h
	PapyrusInterfaces.h
	PapyrusKeyword.h
	PapyrusLeveledActor.h
	PapyrusLeveledItem.h
	PapyrusLeveledSpell.h
	PapyrusLocation.h
	PapyrusMagicEffect.h
	PapyrusMath.h
	PapyrusMisc.h
	PapyrusModEvent.h
	PapyrusNativeFunctionDef.inl
	PapyrusNativeFunctionDef_Base.inl
	PapyrusNativeFunctions.h
	PapyrusNetImmerse.h
	PapyrusObjectReference.h
	PapyrusObjects.h
	PapyrusPerk.h
	PapyrusPotion.h
	PapyrusQuest.h
	PapyrusRace.h
	PapyrusReferenceAlias.h
	PapyrusSKSE.h
	PapyrusScroll.h
	PapyrusShout.h
	PapyrusSound.h
	PapyrusSoundDescriptor.h
	PapyrusSpawnerTask.h
	PapyrusSpell.h
	PapyrusStringUtil.h
	PapyrusTextureSet.h
	PapyrusTree.h
	PapyrusUI.h
	PapyrusUICallback.h
	PapyrusUtility.h
	PapyrusVM.h
	PapyrusValue.h
	PapyrusWeapon.h
	PapyrusWeather.h
	PapyrusWornObject.h
	PluginAPI.h
	PluginManager.h
	ScaleformAPI.h
	ScaleformCallbacks.h
	ScaleformExtendedData.h
	ScaleformLoader.h
	ScaleformMovie.h
	ScaleformState.h
	ScaleformTypes.h
	ScaleformVM.h
	ScaleformValue.h
	Serialization.h
	Translation.h
	gamethreads.h
)
