set(sources
	BSModelDB.cpp
	Colors.cpp
	CustomMenu.cpp
	GameAPI.cpp
	GameBSExtraData.cpp
	GameCamera.cpp
	GameData.cpp
	GameEvents.cpp
	GameExtraData.cpp
	GameFormComponents.cpp
	GameForms.cpp
	GameHandlers.cpp
	GameInput.cpp
	GameMenus.cpp
	GameObjects.cpp
	GamePathing.cpp
	GameRTTI.cpp
	GameReferences.cpp
	GameResources.cpp
	GameSettings.cpp
	GameStreams.cpp
	GameThreads.cpp
	GameTypes.cpp
	GameUtilities.cpp
	GlobalLocks.cpp
	HashUtil.cpp
	Hooks_Camera.cpp
	Hooks_Data.cpp
	Hooks_Debug.cpp
	Hooks_Diagnostics.cpp
	Hooks_DirectInput8Create.cpp
	Hooks_Event.cpp
	Hooks_Gameplay.cpp
	Hooks_Handlers.cpp
	Hooks_Memory.cpp
	Hooks_NetImmerse.cpp
	Hooks_ObScript.cpp
	Hooks_Papyrus.cpp
	Hooks_SaveLoad.cpp
	Hooks_Scaleform.cpp
	Hooks_Threads.cpp
	Hooks_UI.cpp
	InputMap.cpp
	InternalSerialization.cpp
	InternalTasks.cpp
	NiAdditionalGeometryData.cpp
	NiControllers.cpp
	NiExtraData.cpp
	NiGeometry.cpp
	NiInterpolators.cpp
	NiLight.cpp
	NiMaterial.cpp
	NiNodes.cpp
	NiObjects.cpp
	NiProperties.cpp
	NiRTTI.cpp
	NiRenderer.cpp
	NiSerialization.cpp
	NiTextures.cpp
	NiTypes.cpp
	ObScript.cpp
	PapyrusActiveMagicEffect.cpp
	PapyrusActor.cpp
	PapyrusActorBase.cpp
	PapyrusActorValueInfo.cpp
	PapyrusAlias.cpp
	PapyrusAmmo.cpp
	PapyrusArgs.cpp
	PapyrusArmor.cpp
	PapyrusArmorAddon.cpp
	PapyrusArt.cpp
	PapyrusBook.cpp
	PapyrusCamera.cpp
	PapyrusCell.cpp
	PapyrusClass.cpp
	PapyrusColorForm.cpp
	PapyrusCombatStyle.cpp
	PapyrusConstructibleObject.cpp
	PapyrusDefaultObjectManager.cpp
	PapyrusDelayFunctors.cpp
	PapyrusEnchantment.cpp
	PapyrusEquipSlot.cpp
	PapyrusEvents.cpp
	PapyrusFaction.cpp
	PapyrusFlora.cpp
	PapyrusForm.cpp
	PapyrusFormList.cpp
	PapyrusGame.cpp
	PapyrusGameData.cpp
	PapyrusHeadPart.cpp
	PapyrusIngredient.cpp
	PapyrusInput.cpp
	PapyrusInterfaces.cpp
	PapyrusKeyword.cpp
	PapyrusLeveledActor.cpp
	PapyrusLeveledItem.cpp
	PapyrusLeveledSpell.cpp
	PapyrusLocation.cpp
	PapyrusMagicEffect.cpp
	PapyrusMath.cpp
	PapyrusMisc.cpp
	PapyrusModEvent.cpp
	PapyrusNativeFunctions.cpp
	PapyrusNetImmerse.cpp
	PapyrusObjectReference.cpp
	PapyrusObjects.cpp
	PapyrusPerk.cpp
	PapyrusPotion.cpp
	PapyrusQuest.cpp
	PapyrusRace.cpp
	PapyrusReferenceAlias.cpp
	PapyrusSKSE.cpp
	PapyrusScroll.cpp
	PapyrusShout.cpp
	PapyrusSound.cpp
	PapyrusSoundDescriptor.cpp
	PapyrusSpawnerTask.cpp
	PapyrusSpell.cpp
	PapyrusStringUtil.cpp
	PapyrusTextureSet.cpp
	PapyrusTree.cpp
	PapyrusUI.cpp
	PapyrusUICallback.cpp
	PapyrusUtility.cpp
	PapyrusVM.cpp
	PapyrusValue.cpp
	PapyrusWeapon.cpp
	PapyrusWeather.cpp
	PapyrusWornObject.cpp
	PluginManager.cpp
	ScaleformAPI.cpp
	ScaleformCallbacks.cpp
	ScaleformExtendedData.cpp
	ScaleformLoader.cpp
	ScaleformMovie.cpp
	ScaleformState.cpp
	ScaleformTypes.cpp
	ScaleformVM.cpp
	ScaleformValue.cpp
	Serialization.cpp
	Translation.cpp
	skse64.cpp
)
