set(SKSE_VERSION_MAJOR 2)
set(SKSE_VERSION_MINOR 3)
set(SKSE_VERSION_PATCH 1)

set(RUNTIME_VERSION_MAJOR 1)
set(RUNTIME_VERSION_MINOR 7)
set(RUNTIME_VERSION_PATCH 104)
set(RUNTIME_VERSION_TYPE 0)

math(
	EXPR
	RUNTIME_VERSION_PACKED
	"((${RUNTIME_VERSION_MAJOR} & 0xFF) << 24) | ((${RUNTIME_VERSION_MINOR} & 0xFF) << 16) | ((${RUNTIME_VERSION_PATCH} & 0xFFF) << 4) | (${RUNTIME_VERSION_TYPE} & 0xF)"
	OUTPUT_FORMAT
		HEXADECIMAL
)
